### ISSUE TITLE
Add `.!toNum` identifier to set field as num

### ISSUE THREAD

**Issue by tsinis** [myConsciousness/freezer#61]
# 1. Problem to solve

Thanks for your package! Sometimes APIs can return values as `int` OR as a `double`. Dart can handle both cases as a `num` type. So it could be nice to have the ability to annotate keys with a `.!toNum` flag.

# 2. Proposal

Please add the ability to annotate keys with a `.!toNum` (similarly to `.!toDateTime` from #34).

When we specify like below:

```json
{
	"something": {
		"number.!toNum": 0
	}
}
```

It should generate code as:

```dart
class Something {
	const Something(
		num? number,
	);
}
```

# 3. More information

**Comment by myConsciousness** [comment]
Hi @tsinis ,

Thanks for you feedback! I feel this is a very useful feature, I will try to add this as soon as possible :)
